apiVersion: v2
appVersion: "2.16.1"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 10.9.4
description: Container management made easy
home: https://truecharts.org/docs/charts/stable/portainer-ce
icon: https://truecharts.org/img/hotlink-ok/chart-icons/portainer-ce.png
keywords:
  - portainer
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: portainer-ce
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/portainer-ce
  - https://docs.portainer.io/v/ce-2.11/start/install/server/kubernetes/baremetal
  - https://hub.docker.com/r/portainer/portainer-ce
version: 2.0.3
annotations:
  truecharts.org/catagories: |
    - management
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
